import terminal
import time
import turtle

print("Problem 1 - MadLib")
print("="*50)
print("")
name = input("Enter your name: ")
verb =  input("Enter a verb: ")
animal = input("Enter an animal: ")
feeling = input("Enter a feeling (like angry or suprised): ")
name2 = input("Enter another name: ")
feeling2 = input("Enter another feeling (like happy or sad): ")
print("")
print("one day,", name, "was", verb, "in the forest when a", animal, "shows up.", name, "was", feeling, "but he/she was able to tame the", animal, "for some reason. The animal, who we shall name", name2 + ", was", feeling2, "that he was tamed, but/so he went with it anyways.")
input("Ready? ")
terminal.clear()
print("")
print("Problem 2 - Castles and Carpets")
print("="*50)
print("")
A = input("In the King’s palace, there is a square room. There are 2 square identical columns in this room. The side of the room is A. The side of each of the columns is B. The floor of this room is covered with blue carpet except for the parts covered by the columns. I will figure out the area of the carpet. First off, define A: ")
B = input("Now, define B: ")
print("")
print("Calculating area of room...")
time.sleep(2)
roomarea = int(A) * int(A)
print("Calculating area of columns...")
time.sleep(3)
columnsarea = int(B) * int(B)  * 2
print("Calculating area of carpet...")
time.sleep(4)
carpetarea = roomarea - columnsarea
print("The area of the carpet is", carpetarea, "square units.")
input("Ready? ")
terminal.clear()
print("")
print("Problem 3 -" , "e" * 12)
print("="*50)
print("")
wordtomultiply = input("Enter a word: ")
print("")
for i in range(1, 13):
  print(wordtomultiply)
input("Ready? ")
terminal.clear()
print("")
print("Problem 4 + 5 - Turtle")
print("="*50)
print("")
print("Look at turtle")
t = turtle.Turtle()
t.speed(1)
turtle.setup(500,500)
t.penup()
t.pencolor("green")
t.backward(200)
t.left(90)
t.forward(200)
t.right(90)
t.pendown()
for i in range(1, 6):
  t.forward(100)
  t.right(180 - 36)
t.penup()
t.forward(200)
t.pendown()
for i in range(1, 6):
  t.forward(50)
  t.right(360/5)
t.penup()
t.right(90)
t.forward(200)
t.right(90)
t.pendown()
t.pencolor("red")
for i in range(1, 6):
  t.forward(20)
  t.right(90)
  t.pencolor("blue")
  t.forward(20)
  t.left(90)
  t.pencolor("green")
  t.forward(20)
  t.left(90)
  t.pencolor("yellow")
  t.forward(20)
  t.right(90)
  t.pencolor("red")

time.sleep(20)
