import terminal
import time
import math
print("")
print("Problem 1 - Explore Google Classroom")
print("="*50)
print("")
print("uhh")
time.sleep(3)
terminal.clear()
print("Problem 2 - 3 Variables")
print("="*50)
print("")
intvar = input("Enter Number: ")
strvar = input("Enter String: ")
floatvar = input("Enter Float: ")
print("")
print("integer: ", intvar)
print("string: ", strvar)
print("float: ", floatvar)
time.sleep(3)
terminal.clear()
print("Problem 3 - Rectangle")
print("="*50)
print("")
length = input("Enter Length: ")
width = input("Enter Width: ")
print("")
print("Area: ", int(length) * int(width))
print("Perimeter: ", (int(length) * 2) + (int(width) * 2))
time.sleep(3)
terminal.clear()
print("Problem 4 - Magic Bean")
print("="*50)
print("")
height = input("the Magic bean is a plant that doubles in size every day. How big is the bean at the start (in meters)? ")
print("")
print("After 1 day: ", int(height) * 2, "m")
print("After 2 days: ", int(height) * 4, "m")
print("After 3 days: ", int(height) * 8, "m")
print("After 4 days: ", int(height) * 16, "m")
print("After 5 days: ", int(height) * 32, "m")
print("After 6 days: ", int(height) * 64, "m")
print("After 7 days: ", int(height) * 128, "m")
print("After 8 days: ", int(height) * 256, "m")
print("After 9 days: ", int(height) * 512, "m")
print("After 10 days: ", int(height) * 1024, "m")
time.sleep(10)
terminal.clear()
print("Problem 5 - Python")
print("="*50)
print("")
pylength = input("There is a pyhton at the zoo. A vet measured the pythons length to be N inches. Define N: ")
print("")
print("The python is", math.floor(int(pylength) / 12), "full feet long")
time.sleep(3)
terminal.clear()
print("Problem 6 - Money Converter (LEMONLAND IS BACK!!!!)")
print("="*50)
print("")
minidoolars = input("In lemonland, 1 doolar is worth 50 minidoolars. How many minidoolars do you have? ")
print("")
print("You have", math.floor(int(minidoolars) / 50), "doolars")
print("with an extra", int(minidoolars) % 50, "minidoolars")
